### ISSUE TITLE
The use of canvas's translate.

### ISSUE THREAD

**Issue by CoXier** [maoruibin/FlowerLoading#1]
```java
    @Override
    public void draw(Canvas canvas) {
        canvas.save();
        canvas.translate(getBounds().left, getBounds().top);
        canvas.drawBitmap(mSource, mMatrix, null);
        canvas.restore();
    }
```
Why should canvas translate?

**Comment by maoruibin** [comment]
In most case, left and top value is zero, and it has no problems, but in some condition, you want change drawable's position by setBounds() method, for example,  you want to use LoadingDrawable as TextView's  CompoundDrawable, and want to show it in center position, in this condition, you would set bounds to make it center, but if not follow the above way,  the LoadingDrawable will show TextView's left side never.

**Comment by CoXier** [comment]
Thanks, I get it.
