### ISSUE TITLE
The size of bitmap

### ISSUE THREAD

**Issue by CoXier** [maoruibin/FlowerLoading#3]
```java
    public LoadingDrawable(Context context, int resDrawable) {
        this.mContext = context;
        this.mSource = BitmapFactory.decodeResource(mContext.getResources(), resDrawable);
        mHandler = new Handler();
        mLoadingTask = new LoadingTask(this);
    }
```
I think we should provide `decode options`  for user because in some case the user know the size but we don't know.**Additionally if the resource is very large , the memory size will increase and it will also take much time to decode.**

```java
    private void onSizeChanged(int w, int h, int drawableWidth, int drawableHeight) {
        if (w != h) {
            throw new IllegalStateException("view must have same width and height, now w = " + w
                    + " h =" + h);
        }
        mCenterXY = w / 2;
        if (drawableWidth != drawableHeight) {
            throw new IllegalStateException("drawable must have same width and height, now " +
                    "drawableWidth = " + drawableWidth + " drawableHeight=" + drawableHeight);
        }
      .....
}
```
DO you mean the resource's width and height must be same? I think it's better to check when construct `LoadingDrawable`.

**Comment by maoruibin** [comment]
* 1、you are right, but considering that loading view are generally small pic, so now we can keep this design. 

* 2、Yes, drawable resource must be same width and height, and as you say move this check in construct method is more reasonable.
